/** Auth mutation error codes (login, register, password reset). */
export const AUTH_MUTATION_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TERMS_REQUIRED: "TERMS_REQUIRED",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  VALIDATION: "VALIDATION",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
} as const;

export type AuthMutationErrorCode =
  (typeof AUTH_MUTATION_ERROR_CODES)[keyof typeof AUTH_MUTATION_ERROR_CODES];

/** Wishlist mutation error codes. */
export const WISHLIST_MUTATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TRAINER_NOT_BOOKABLE: "TRAINER_NOT_BOOKABLE",
  VALIDATION: "VALIDATION",
} as const;

export type WishlistMutationErrorCode =
  (typeof WISHLIST_MUTATION_ERROR_CODES)[keyof typeof WISHLIST_MUTATION_ERROR_CODES];

/** Booking mutation error codes. */
export const BOOKING_MUTATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION: "VALIDATION",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  TRAINER_NOT_BOOKABLE: "TRAINER_NOT_BOOKABLE",
  SERVICE_INACTIVE: "SERVICE_INACTIVE",
  SLOT_IN_PAST: "SLOT_IN_PAST",
  CANCELLATION_WINDOW_CLOSED: "CANCELLATION_WINDOW_CLOSED",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  BOOKING_TERMINAL: "BOOKING_TERMINAL",
  BOOKING_STATE_CONFLICT: "BOOKING_STATE_CONFLICT",
} as const;

export type BookingMutationErrorCode =
  (typeof BOOKING_MUTATION_ERROR_CODES)[keyof typeof BOOKING_MUTATION_ERROR_CODES];

/** Review mutation error codes. */
export const REVIEW_MUTATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION: "VALIDATION",
  BOOKING_NOT_REVIEWABLE: "BOOKING_NOT_REVIEWABLE",
  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",
} as const;

export type ReviewMutationErrorCode =
  (typeof REVIEW_MUTATION_ERROR_CODES)[keyof typeof REVIEW_MUTATION_ERROR_CODES];

/** Trainer onboarding / verification mutation error codes. */
export const TRAINER_MUTATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION: "VALIDATION",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  ALREADY_APPROVED: "ALREADY_APPROVED",
  APPLICATION_INCOMPLETE: "APPLICATION_INCOMPLETE",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  ALREADY_SUBMITTED: "ALREADY_SUBMITTED",
} as const;

export type TrainerMutationErrorCode =
  (typeof TRAINER_MUTATION_ERROR_CODES)[keyof typeof TRAINER_MUTATION_ERROR_CODES];

/** Trainer service mutation error codes. */
export const TRAINER_SERVICE_MUTATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION: "VALIDATION",
  NOT_FOUND: "NOT_FOUND",
  SERVICE_HAS_BOOKINGS: "SERVICE_HAS_BOOKINGS",
} as const;

export type TrainerServiceMutationErrorCode =
  (typeof TRAINER_SERVICE_MUTATION_ERROR_CODES)[keyof typeof TRAINER_SERVICE_MUTATION_ERROR_CODES];

/** File upload mutation error codes. */
export const FILE_UPLOAD_MUTATION_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION: "VALIDATION",
  INVALID_MIME: "INVALID_MIME",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  INVALID_UPLOAD_STATE: "INVALID_UPLOAD_STATE",
} as const;

export type FileUploadMutationErrorCode =
  (typeof FILE_UPLOAD_MUTATION_ERROR_CODES)[keyof typeof FILE_UPLOAD_MUTATION_ERROR_CODES];

/** All known mutation error codes — extend as domains ship. */
export const MUTATION_ERROR_CODES = {
  ...AUTH_MUTATION_ERROR_CODES,
  ...WISHLIST_MUTATION_ERROR_CODES,
  ...BOOKING_MUTATION_ERROR_CODES,
  ...REVIEW_MUTATION_ERROR_CODES,
  ...TRAINER_MUTATION_ERROR_CODES,
  ...TRAINER_SERVICE_MUTATION_ERROR_CODES,
  ...FILE_UPLOAD_MUTATION_ERROR_CODES,
} as const;

export type MutationErrorCode =
  (typeof MUTATION_ERROR_CODES)[keyof typeof MUTATION_ERROR_CODES];
